version: '2'
services:
  mariadb:
    container_name: inethi-mariadb
    image: docker.io/bitnami/mariadb:10.5
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - '${MOODLE_VOLUME}/mariadb_data:/bitnami/mariadb'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mariadb.rule=Host(`${TRAEFIK_API_RULE_MARIADB}`)"
      - "traefik.http.routers.mariadb.entrypoints=${TRAEFIK_ENTRYPOINT}"

  moodle:
    container_name: inethi-moodle
    image: docker.io/bitnami/moodle:3
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '${MOODLE_VOLUME}/moodle_data:/bitnami/moodle'
      - '${MOODLE_VOLUME}/moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle.rule=Host(`${TRAEFIK_API_RULE_MOODLE}`)"
      - "traefik.http.routers.moodle.entrypoints=${TRAEFIK_ENTRYPOINT}"

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"
